api_platform:
  resource_class_directories:
    - '%kernel.project_dir%/src/Syllabus/Entity'
  collection:
    pagination:
      client_items_per_page: true # Disabled by default
      items_per_page_parameter_name: itemsPerPage # Default value