doctrine:
  dbal:
    default_connection: syllabus
    connections:
      syllabus:
        url: '%env(resolve:DATABASE_SYLLABUS_URL)%'
      apogee:
        url: '%env(resolve:DATABASE_APOGEE_URL)%'
        logging: false
        profiling: false
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    #naming_strategy: doctrine.orm.naming_strategy.underscore
    #auto_mapping: true
    default_entity_manager: syllabus
    entity_managers:
      syllabus:
        connection: syllabus
        auto_mapping: true
        mappings:
          Syllabus:
            type: attribute
            is_bundle: false
            prefix: 'App\Syllabus\Entity'
            dir: "%kernel.project_dir%/src/Syllabus/Entity"
            alias: Syllabus
          translatable:
            type: attribute
            is_bundle: false
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
            alias: GedmoTranslatable
          DmishhSettingsBundle: ~
    controller_resolver:
      auto_mapping: true
    enable_lazy_ghost_objects: true