doctrine:
  dbal:
    default_connection: syllabus
    connections:
      syllabus:
        driver: '%env(SYLLABUS_DATABASE_DRIVER)%'
        host: '%env(SYLLABUS_DATABASE_HOST)%'
        port: '%env(SYLLABUS_DATABASE_PORT)%'
        dbname: '%env(SYLLABUS_DATABASE_NAME)%'
        user: '%env(SYLLABUS_DATABASE_USER)%'
        password: '%env(SYLLABUS_DATABASE_PASSWORD)%'
        charset: '%env(SYLLABUS_DATABASE_CHARSET)%'
      apogee:
        driver: '%env(APOGEE_DATABASE_DRIVER)%'
        host: '%env(APOGEE_DATABASE_HOST)%'
        port: '%env(APOGEE_DATABASE_PORT)%'
        dbname: '%env(APOGEE_DATABASE_NAME)%'
        user: '%env(APOGEE_DATABASE_USER)%'
        password: '%env(APOGEE_DATABASE_PASSWORD)%'
        charset: '%env(APOGEE_DATABASE_CHARSET)%'
        logging: false
        profiling: false
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    #naming_strategy: doctrine.orm.naming_strategy.underscore
    #auto_mapping: true
    default_entity_manager: syllabus
    entity_managers:
      syllabus:
        connection: syllabus
        auto_mapping: true
        mappings:
          Syllabus:
            type: annotation
            is_bundle: false
            prefix: 'App\Syllabus\Entity'
            dir: "%kernel.project_dir%/src/Syllabus/Entity"
            alias: Syllabus
          translatable:
            type: annotation
            is_bundle: false
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
            alias: GedmoTranslatable
          DmishhSettingsBundle: ~
      apogee:
        connection: apogee
        auto_mapping: false
        mappings:
          UniceSILSyllabusApogeeImporterBundle: ~
