framework:
  #esi: ~
  secret: '%env(APP_SECRET)%'

  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    cookie_lifetime: 3600

  php_errors:
    log: true

  serializer: { enable_annotations: true }
