lexik_translation:
  fallback_locale: '%env(json:FALLBACK_LOCALES)%'         # (required) default locale(s) to use
  managed_locales: '%env(json:MANAGED_LOCALES)%' # (required) locales that the bundle has to manage
  storage:
    type: orm                  # orm | mongodb | propel
    object_manager: syllabus
