security:
    enable_authenticator_manager: true

    password_hashers:
        App\Syllabus\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: '%provider%'
        user_db:
            entity: { class: App\Syllabus\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            lazy: true
            json_login:
                check_path:         /api/login_check
                username_path:      username
                password_path:      password
                success_handler:    lexik_jwt_authentication.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure
                provider:           user_db
        api:
            pattern: ^/api/(?!docs.+/?)
            stateless: true
            provider: user_db
            jwt: ~
        main:
            pattern: ^/
            lazy: true
            provider: main
            logout:
                path: /logout
            custom_authenticators:
                - '%authenticator%'

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_API:
            - ROLE_API_GET_YEARS
            - ROLE_API_GET_YEAR
            - ROLE_API_POST_YEAR
            - ROLE_API_PUT_YEAR
            - ROLE_API_DUPLICATE_SYLLABUS

    access_control:
        - { path: light(\/.*)?$, roles: PUBLIC_ACCESS }
        - { path: /maintenance$, roles: PUBLIC_ACCESS }
        - { path: /search-courses$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api(/docs)?$, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: ROLE_API }
        - { path: "^/[^/]{1,5}/admin/settings", role: ROLE_SUPER_ADMIN }
        - { path: "^/[^/]{1,5}/admin", role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
