twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    regulation_link : '%env(REGULATION_LINK)%'
    app_version: prototype
    managed_locales: '%env(json:MANAGED_LOCALES)%'
  form_themes:
    - 'bootstrap_4_layout.html.twig'
    - '@TetranzSelect2Entity/Form/fields.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - '@LexikFormFilter/Form/form_div_layout.html.twig'
