twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  globals:
    tutorial_link_syllabus_dashboard: '%env(TUTORIAL_LINK_SYLLABUS_DASHBOARD)%'
    tutorial_link_mail_published: '%env(TUTORIAL_LINK_MAIL_PUBLISHED)%'
    tutorial_link_syllabus_issue: '%env(TUTORIAL_LINK_SYLLABUS_ISSUE)%'
    tutorial_link_presentation_video: '%env(TUTORIAL_LINK_PRESENTATION_VIDEO)%'
    regulation_link : '%env(REGULATION_LINK)%'
    app_version: prototype
    managed_locales: '%managed_locales%'
  form_themes:
    - 'bootstrap_4_layout.html.twig'
    - '@TetranzSelect2Entity/Form/fields.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - '@LexikFormFilter/Form/form_div_layout.html.twig'
