<?php

namespace AppBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;

/**
 * TeachingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeachingDoctrineRepository extends EntityRepository
{
}
