imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@LdapBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    fos_ck_editor.base_path: 'build/ckeditor'
    fos_ck_editor.js_path: 'build/ckeditor/ckeditor.js'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true, enabled: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 3600
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        regulation_link : '%regulation_link%'
        app_version: prototype
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@LexikFormFilter/Form/form_div_layout.html.twig'

# Doctrine Configuration

doctrine:
    dbal:
        default_connection: syllabus
        connections:
            syllabus:
                driver: '%syllabus_database_driver%'
                host: '%syllabus_database_host%'
                port: '%syllabus_database_port%'
                dbname: '%syllabus_database_name%'
                user: '%syllabus_database_user%'
                password: '%syllabus_database_password%'
                charset: '%syllabus_database_charset%'
            apogee:
                driver: oci8
                host: 'apoprod.prive.unice.fr'
                port: '15010'
                dbname: 'apoprod'
                user: 'apogee'
                password: '6cdur7ok'
                charset: UTF8
        types:
            apogeeDate: UniceSIL\SyllabusApogeeImporterBundle\Doctrine\DBAL\Types\ApogeeDateType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        default_entity_manager: syllabus
        entity_managers:
            syllabus:
                connection: syllabus
                auto_mapping: false
                mappings:
                    AppBundle: ~
                    DmishhSettingsBundle: ~
            apogee:
                connection: apogee
                auto_mapping: false
                mappings:
                    UniceSILSyllabusApogeeImporterBundle: ~

doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    namespace: DoctrineMigrations
    table_name: 'migration_versions'
    column_name: 'version'
    column_length: 14
    executed_at_column_name: 'executed_at'
    name: 'Application Migrations'
    # available in version >= 1.2. Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false
    # available in version >= 1.3. Path to your custom migrations template
    custom_template: ~
    all_or_nothing: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    router:
        annotations: false
    security:
        annotations: true

webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    #output_path: '%kernel.public_dir%/build' -> S4 syntax…
    output_path: '%kernel.project_dir%/web/build'

    # if you have multiple builds:
    # builds:
        # pass "frontend" as the 3rg arg to the Twig functions
        # {{ encore_entry_script_tags('entry1', null, 'frontend') }}

        # frontend: '%kernel.public_dir%/frontend/build'

fos_ck_editor:
    base_path: '%fos_ck_editor.base_path%'
    js_path: '%fos_ck_editor.js_path%'
    default_config: syllabus
    configs:
        syllabus:
            toolbar: course_summary
            removeButtons:
            removePlugins: 'elementspath'
            resize_enabled: false
    toolbars:
        configs:
            course_summary: [ '@basicstyles', '-', '@paragraphs', '-', '@link' ]
        items:
            link: [ 'Link' ]
            basicstyles: [ 'RemoveFormat', '-', 'Bold', 'Italic', 'Underline' ]
            paragraphs: [ 'Outdent', 'Indent', '-', 'NumberedList', 'BulletedList' ]

unice_sil_syllabus_apogee_importer:
    em: apogee
    course:
        types: [ 'ECUE', 'UE' ]

unice_sil_shibboleth:
    login_path: 'Shibboleth.sso/Login'  # The path used to call Shibboleth login authentication (default = 'Shibboleth.sso/Login')
    logout_path: 'Shibboleth.sso/Login'  # The path used to call Shibboleth logout (default = 'Shibboleth.sso/Logout')
    username: 'eppn'  # The Shibboleth attribute that is used as username for the logged in user. The attribute must appear in the'attributes' parameter list (default = 'username')
    attributes: ['eppn', 'mail', 'givenName', 'sn', 'uid', 'unscoped-affiliation']  # The list of attributes returned by Shibboleth Service Provider
    login_target : ''  # The route to which the user will be redirected after login. If this parameter is not filled, the user will be redirected to the page from which he comes. (default = null)
    logout_target : ''  # The route to which the user will be redirected after logout. If this parameter is not filled, the user will be redirected to the page from which he comes. (default = null)

knp_paginator:
    template:
        pagination: 'partial/_pagination.html.twig'

lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/app/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/app/config/jwt/public.pem'  # required for token verification
    pass_phrase:      '%jwt_authentication_passphrase%' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600
    user_identity_field: username

nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)

    documentation:
        host: '%api_host%'
        schemes: [http, https]
        info:
            title: '%app_name%'
            description: Find wahtever you want about the %app_name% api in this documentation
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []

stof_doctrine_extensions:
    orm:
        syllabus:
            timestampable: true
            blameable: true

jms_serializer:
    object_constructors:
        doctrine:
            fallback_strategy: "exception" # possible values ("null" | "exception" | "fallback")
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    handlers:
        datetime:
            default_format: "Y-m-d h:i:s" # ISO8601

dmishh_settings:
    template: 'setting/manage.html.twig'
    cache_service: null
    cache_lifetime: 3600
    security:
        manage_global_settings_role: ROLE_USER
        users_can_manage_own_settings: true
    serialization: php # database serialization mechanism (php|json)
    settings:
        in_maintenance:
            scope: all # global or user
            type: AppBundle\Form\Type\CustomCheckboxType # any Symfony form type, or FQCN for Symfony >=3.0
            options: # options passed to form
                required: false
        #            constraints:
        #                Symfony\Component\Validator\Constraints\Length:
        #                    min: 5