imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@LdapBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    fos_ck_editor.base_path: 'build/ckeditor'
    fos_ck_editor.js_path: 'build/ckeditor/ckeditor.js'

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        regulation_link : '%regulation_link%'
        app_version: prototype
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: syllabus
        connections:
            syllabus:
                driver: '%syllabus_database_driver%'
                host: '%syllabus_database_host%'
                port: '%syllabus_database_port%'
                dbname: '%syllabus_database_name%'
                user: '%syllabus_database_user%'
                password: '%syllabus_database_password%'
                charset: '%syllabus_database_charset%'
            apogee:
                driver: pdo_oci
                host: 'apoprod.prive.unice.fr'
                port: '15010'
                dbname: 'apoprod'
                user: 'apogee'
                password: '6cdur7ok'
                charset: UTF8
        types:
            apogeeDate: UniceSIL\SyllabusApogeeImporterBundle\Doctrine\DBAL\Types\ApogeeDateType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        default_entity_manager: syllabus
        entity_managers:
            syllabus:
                connection: syllabus
                auto_mapping: false
                mappings:
                    AppBundle: ~
            apogee:
                connection: apogee
                auto_mapping: false
                mappings:
                    UniceSILSyllabusApogeeImporterBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    router:
        annotations: false

webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    #output_path: '%kernel.public_dir%/build' -> S4 syntax…
    output_path: '%kernel.project_dir%/web/build'

    # if you have multiple builds:
    # builds:
        # pass "frontend" as the 3rg arg to the Twig functions
        # {{ encore_entry_script_tags('entry1', null, 'frontend') }}

        # frontend: '%kernel.public_dir%/frontend/build'

fos_ck_editor:
    base_path: '%fos_ck_editor.base_path%'
    js_path: '%fos_ck_editor.js_path%'
    default_config: syllabus
    configs:
        syllabus:
            toolbar: course_summary
            removeButtons:
            removePlugins: 'elementspath'
            resize_enabled: false
    toolbars:
        configs:
            course_summary: [ '@basicstyles', '-', '@paragraphs', '-', '@link' ]
        items:
            link: [ 'Link' ]
            basicstyles: [ 'RemoveFormat', '-', 'Bold', 'Italic', 'Underline' ]
            paragraphs: [ 'Outdent', 'Indent', '-', 'NumberedList', 'BulletedList' ]

unice_sil_syllabus_apogee_importer:
    em: apogee
    course:
        types: [ 'ECUE', 'UE' ]