app_year:
    resource: "@AppBundle/Controller/YearController.php"
    type:     annotation

app:
    resource: '@AppBundle/Action/'
    type: annotation

syllabus:
    resource: '@AppBundle/Controller/'
    type: annotation