app_cron:
    resource: "@AppBundle/Controller/CronController.php"
    type:     annotation

app_year:
    resource: "@AppBundle/Controller/YearController.php"
    type:     annotation

syllabus:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }