## L'ordre a une importance !!!!!!!!!!
syllabus:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'

syllabus.admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation
    prefix: /{_locale}/admin
    defaults:
        _locale: '%locale%'

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin/translation
    defaults:
        _locale: '%locale%'

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }