syllabus:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

settings:
    resource: "@DmishhSettingsBundle/Resources/config/routing.yml"
    prefix: /admin/settings

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }