# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        test:
            id: AppBundle\Security\Provider\TestUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            guard:
                authenticator: AppBundle\Security\Authenticator\TestAuthenticator
                provider: test
            anonymous: ~

    access_control:
        - { path: ^/, role: ROLE_ADMIN }
