<?php


namespace App\Syllabus\Constant;

/**
 * Class UserRole
 * @package AppBundle\Constant
 */
class UserRole
{
    /*====================== USER ROLES ==================*/
    const ROLE_USER = 'ROLE_USER';

    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    /*====================== ADMIN ROLES ==================*/
    const ROLE_ADMIN = 'ROLE_ADMIN';

    // COURSE
    const ROLE_ADMIN_COURSE = 'ROLE_ADMIN_COURSE';
    const ROLE_ADMIN_COURSE_LIST = 'ROLE_ADMIN_COURSE_LIST';
    const ROLE_ADMIN_COURSE_VIEW = 'ROLE_ADMIN_COURSE_VIEW';
    const ROLE_ADMIN_COURSE_CREATE = 'ROLE_ADMIN_COURSE_CREATE';
    const ROLE_ADMIN_COURSE_UPDATE = 'ROLE_ADMIN_COURSE_UPDATE';

    // COURSE_INFO
    const ROLE_ADMIN_COURSE_INFO = 'ROLE_ADMIN_COURSE_INFO';
    const ROLE_ADMIN_COURSE_INFO_LIST = 'ROLE_ADMIN_COURSE_INFO_LIST';
    const ROLE_ADMIN_COURSE_INFO_CREATE = 'ROLE_ADMIN_COURSE_INFO_CREATE';
    const ROLE_ADMIN_COURSE_INFO_UPDATE = 'ROLE_ADMIN_COURSE_INFO_UPDATE';

    // YEARS
    const ROLE_ADMIN_YEAR = 'ROLE_ADMIN_YEAR';
    const ROLE_ADMIN_YEAR_LIST = 'ROLE_ADMIN_YEAR_LIST';
    const ROLE_ADMIN_YEAR_CREATE = 'ROLE_ADMIN_YEAR_CREATE';
    const ROLE_ADMIN_YEAR_UPDATE = 'ROLE_ADMIN_YEAR_UPDATE';

    // CRITICAL ACHIEVEMENTS
    const ROLE_ADMIN_CRITICAL_ACHIEVEMENT = 'ROLE_ADMIN_CRITICAL_ACHIEVEMENT';
    const ROLE_ADMIN_CRITICAL_ACHIEVEMENT_LIST = 'ROLE_ADMIN_CRITICAL_ACHIEVEMENT_LIST';
    const ROLE_ADMIN_CRITICAL_ACHIEVEMENT_CREATE = 'ROLE_ADMIN_CRITICAL_ACHIEVEMENT_CREATE';
    const ROLE_ADMIN_CRITICAL_ACHIEVEMENT_UPDATE = 'ROLE_ADMIN_CRITICAL_ACHIEVEMENT_UPDATE';

    // ACTIVITIES
    const ROLE_ADMIN_ACTIVITY = 'ROLE_ADMIN_ACTIVITY';
    const ROLE_ADMIN_ACTIVITY_LIST = 'ROLE_ADMIN_ACTIVITY_LIST';
    const ROLE_ADMIN_ACTIVITY_CREATE = 'ROLE_ADMIN_ACTIVITY_CREATE';
    const ROLE_ADMIN_ACTIVITY_UPDATE = 'ROLE_ADMIN_ACTIVITY_UPDATE';

    // ACTIVITIES MODES
    const ROLE_ADMIN_ACTIVITYMODE = 'ROLE_ADMIN_ACTIVITYMODE';
    const ROLE_ADMIN_ACTIVITYMODE_LIST = 'ROLE_ADMIN_ACTIVITYMODE_LIST';
    const ROLE_ADMIN_ACTIVITYMODE_CREATE = 'ROLE_ADMIN_ACTIVITYMODE_CREATE';
    const ROLE_ADMIN_ACTIVITYMODE_UPDATE = 'ROLE_ADMIN_ACTIVITYMODE_UPDATE';

    // ACTIVITIES TYPES
    const ROLE_ADMIN_ACTIVITYTYPE = 'ROLE_ADMIN_ACTIVITYTYPE';
    const ROLE_ADMIN_ACTIVITYTYPE_LIST = 'ROLE_ADMIN_ACTIVITYTYPE_LIST';
    const ROLE_ADMIN_ACTIVITYTYPE_CREATE = 'ROLE_ADMIN_ACTIVITYTYPE_CREATE';
    const ROLE_ADMIN_ACTIVITYTYPE_UPDATE = 'ROLE_ADMIN_ACTIVITYTYPE_UPDATE';

    // CAMPUSES
    const ROLE_ADMIN_CAMPUS = 'ROLE_ADMIN_CAMPUS';
    const ROLE_ADMIN_CAMPUS_LIST = 'ROLE_ADMIN_CAMPUS_LIST';
    const ROLE_ADMIN_CAMPUS_CREATE = 'ROLE_ADMIN_CAMPUS_CREATE';
    const ROLE_ADMIN_CAMPUS_UPDATE = 'ROLE_ADMIN_CAMPUS_UPDATE';

    // DOMAINS
    const ROLE_ADMIN_DOMAIN = 'ROLE_ADMIN_DOMAIN';
    const ROLE_ADMIN_DOMAIN_LIST = 'ROLE_ADMIN_DOMAIN_LIST';
    const ROLE_ADMIN_DOMAIN_CREATE = 'ROLE_ADMIN_DOMAIN_CREATE';
    const ROLE_ADMIN_DOMAIN_UPDATE = 'ROLE_ADMIN_DOMAIN_UPDATE';

    // EQUIPMENTS
    const ROLE_ADMIN_EQUIPMENT = 'ROLE_ADMIN_EQUIPMENT';
    const ROLE_ADMIN_EQUIPMENT_LIST = 'ROLE_ADMIN_EQUIPMENT_LIST';
    const ROLE_ADMIN_EQUIPMENT_CREATE = 'ROLE_ADMIN_EQUIPMENT_CREATE';
    const ROLE_ADMIN_EQUIPMENT_UPDATE = 'ROLE_ADMIN_EQUIPMENT_UPDATE';


    // JOBS
    const ROLE_ADMIN_JOB = 'ROLE_ADMIN_JOB';
    const ROLE_ADMIN_JOB_LIST = 'ROLE_ADMIN_JOB_LIST';
    const ROLE_ADMIN_JOB_CREATE = 'ROLE_ADMIN_JOB_CREATE';
    const ROLE_ADMIN_JOB_UPDATE = 'ROLE_ADMIN_JOB_UPDATE';
    const ROLE_ADMIN_JOB_DELETE = 'ROLE_ADMIN_JOB_DELETE';
    const ROLE_ADMIN_JOB_EXECUTE = 'ROLE_ADMIN_JOB_EXECUTE';
    const ROLE_ADMIN_JOB_REPORT = 'ROLE_ADMIN_JOB_REPORT';

    // LANGUAGES
    const ROLE_ADMIN_LANGUAGE = 'ROLE_ADMIN_LANGUAGE';
    const ROLE_ADMIN_LANGUAGE_LIST = 'ROLE_ADMIN_LANGUAGE_LIST';
    const ROLE_ADMIN_LANGUAGE_CREATE = 'ROLE_ADMIN_LANGUAGE_CREATE';
    const ROLE_ADMIN_LANGUAGE_UPDATE = 'ROLE_ADMIN_LANGUAGE_UPDATE';

    // NOTIFICATIONS
    const ROLE_ADMIN_NOTIFICATION = 'ROLE_ADMIN_NOTIFICATION';
    const ROLE_ADMIN_NOTIFICATION_LIST = 'ROLE_ADMIN_NOTIFICATION_LIST';
    const ROLE_ADMIN_NOTIFICATION_CREATE = 'ROLE_ADMIN_NOTIFICATION_CREATE';
    const ROLE_ADMIN_NOTIFICATION_UPDATE = 'ROLE_ADMIN_NOTIFICATION_UPDATE';
    const ROLE_ADMIN_NOTIFICATION_DELETE = 'ROLE_ADMIN_NOTIFICATION_DELETE';

    // PERIODS
    const ROLE_ADMIN_PERIOD = 'ROLE_ADMIN_PERIOD';
    const ROLE_ADMIN_PERIOD_LIST = 'ROLE_ADMIN_PERIOD_LIST';
    const ROLE_ADMIN_PERIOD_CREATE = 'ROLE_ADMIN_PERIOD_CREATE';
    const ROLE_ADMIN_PERIOD_UPDATE = 'ROLE_ADMIN_PERIOD_UPDATE';

    // STRUCTURES
    const ROLE_ADMIN_STRUCTURE = 'ROLE_ADMIN_STRUCTURE';
    const ROLE_ADMIN_STRUCTURE_LIST = 'ROLE_ADMIN_STRUCTURE_LIST';
    const ROLE_ADMIN_STRUCTURE_CREATE = 'ROLE_ADMIN_STRUCTURE_CREATE';
    const ROLE_ADMIN_STRUCTURE_UPDATE = 'ROLE_ADMIN_STRUCTURE_UPDATE';

    // USERS
    const ROLE_ADMIN_USER = 'ROLE_ADMIN_USER';
    const ROLE_ADMIN_USER_LIST = 'ROLE_ADMIN_USER_LIST';
    const ROLE_ADMIN_USER_CREATE = 'ROLE_ADMIN_USER_CREATE';
    const ROLE_ADMIN_USER_UPDATE = 'ROLE_ADMIN_USER_UPDATE';

    // LEVELS
    const ROLE_ADMIN_LEVEL = 'ROLE_ADMIN_LEVEL';
    const ROLE_ADMIN_LEVEL_LIST = 'ROLE_ADMIN_LEVEL_LIST';
    const ROLE_ADMIN_LEVEL_CREATE = 'ROLE_ADMIN_LEVEL_CREATE';
    const ROLE_ADMIN_LEVEL_UPDATE = 'ROLE_ADMIN_LEVEL_UPDATE';


    /*====================== API ROLES ==================*/
    const ROLE_API = 'ROLE_API';

    const ROLE_API_ACTIVITY = 'ROLE_API_ACTIVITY';
    const ROLE_API_ACTIVITY_GET = 'ROLE_API_ACTIVITY_GET';
    const ROLE_API_ACTIVITY_POST = 'ROLE_API_ACTIVITY_POST';
    const ROLE_API_ACTIVITY_PUT = 'ROLE_API_ACTIVITY_PUT';
    const ROLE_API_ACTIVITY_DELETE = 'ROLE_API_ACTIVITY_DELETE';

    const ROLE_API_ACTIVITY_MODE = 'ROLE_API_ACTIVITY_MODE';
    const ROLE_API_ACTIVITY_MODE_GET = 'ROLE_API_ACTIVITY_MODE_GET';
    const ROLE_API_ACTIVITY_MODE_POST = 'ROLE_API_ACTIVITY_MODE_POST';
    const ROLE_API_ACTIVITY_MODE_PUT = 'ROLE_API_ACTIVITY_MODE_PUT';
    const ROLE_API_ACTIVITY_MODE_DELETE = 'ROLE_API_ACTIVITY_MODE_DELETE';

    const ROLE_API_ACTIVITY_TYPE = 'ROLE_API_ACTIVITY_TYPE';
    const ROLE_API_ACTIVITY_TYPE_GET = 'ROLE_API_ACTIVITY_TYPE_GET';
    const ROLE_API_ACTIVITY_TYPE_POST = 'ROLE_API_ACTIVITY_TYPE_POST';
    const ROLE_API_ACTIVITY_TYPE_PUT = 'ROLE_API_ACTIVITY_TYPE_PUT';
    const ROLE_API_ACTIVITY_TYPE_DELETE = 'ROLE_API_ACTIVITY_TYPE_DELETE';

    const ROLE_API_ASK_ADVICE = 'ROLE_API_ASK_ADVICE';
    const ROLE_API_ASK_ADVICE_GET = 'ROLE_API_ASK_ADVICE_GET';
    const ROLE_API_ASK_ADVICE_POST = 'ROLE_API_ASK_ADVICE_POST';
    const ROLE_API_ASK_ADVICE_PUT = 'ROLE_API_ASK_ADVICE_PUT';
    const ROLE_API_ASK_ADVICE_DELETE = 'ROLE_API_ASK_ADVICE_DELETE';

    const ROLE_API_CAMPUS = 'ROLE_API_CAMPUS';
    const ROLE_API_CAMPUS_GET = 'ROLE_API_CAMPUS_GET';
    const ROLE_API_CAMPUS_POST = 'ROLE_API_CAMPUS_POST';
    const ROLE_API_CAMPUS_PUT = 'ROLE_API_CAMPUS_PUT';
    const ROLE_API_CAMPUS_DELETE = 'ROLE_API_CAMPUS_DELETE';

    const ROLE_API_COURSE = 'ROLE_API_COURSE';
    const ROLE_API_COURSE_GET = 'ROLE_API_COURSE_GET';
    const ROLE_API_COURSE_POST = 'ROLE_API_COURSE_POST';
    const ROLE_API_COURSE_PUT = 'ROLE_API_COURSE_PUT';
    const ROLE_API_COURSE_DELETE = 'ROLE_API_COURSE_DELETE';

    const ROLE_API_COURSE_ACHIEVEMENT = 'ROLE_API_COURSE_ACHIEVEMENT';
    const ROLE_API_COURSE_ACHIEVEMENT_GET = 'ROLE_API_COURSE_ACHIEVEMENT_GET';
    const ROLE_API_COURSE_ACHIEVEMENT_POST = 'ROLE_API_COURSE_ACHIEVEMENT_POST';
    const ROLE_API_COURSE_ACHIEVEMENT_PUT = 'ROLE_API_COURSE_ACHIEVEMENT_PUT';
    const ROLE_API_COURSE_ACHIEVEMENT_DELETE = 'ROLE_API_COURSE_ACHIEVEMENT_DELETE';

    const ROLE_API_COURSE_CRITICAL_ACHIEVEMENT = 'ROLE_API_COURSE_CRITICAL_ACHIEVEMENT';
    const ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_GET = 'ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_GET';
    const ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_POST= 'ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_POST';
    const ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_PUT = 'ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_PUT';
    const ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_DELETE = 'ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_DELETE';

    const ROLE_API_COURSE_INFO = 'ROLE_API_COURSE_INFO';
    const ROLE_API_COURSE_INFO_GET = 'ROLE_API_COURSE_INFO_GET';
    const ROLE_API_COURSE_INFO_POST = 'ROLE_API_COURSE_INFO_POST';
    const ROLE_API_COURSE_INFO_PUT = 'ROLE_API_COURSE_INFO_PUT';
    const ROLE_API_COURSE_INFO_DELETE = 'ROLE_API_COURSE_INFO_DELETE';

    const ROLE_API_COURSE_INFO_FIELD = 'ROLE_API_COURSE_INFO_FIELD';
    const ROLE_API_COURSE_INFO_FIELD_GET = 'ROLE_API_COURSE_INFO_FIELD_GET';
    const ROLE_API_COURSE_INFO_FIELD_POST = 'ROLE_API_COURSE_INFO_FIELD_POST';
    const ROLE_API_COURSE_INFO_FIELD_PUT = 'ROLE_API_COURSE_INFO_FIELD_PUT';
    const ROLE_API_COURSE_INFO_FIELD_DELETE = 'ROLE_API_COURSE_INFO_FIELD_DELETE';

    const ROLE_API_COURSE_PERMISSION = 'ROLE_API_COURSE_PERMISSION';
    const ROLE_API_COURSE_PERMISSION_GET = 'ROLE_API_COURSE_PERMISSION_GET';
    const ROLE_API_COURSE_PERMISSION_POST = 'ROLE_API_COURSE_PERMISSION_POST';
    const ROLE_API_COURSE_PERMISSION_PUT = 'ROLE_API_COURSE_PERMISSION_PUT';
    const ROLE_API_COURSE_PERMISSION_DELETE = 'ROLE_API_COURSE_PERMISSION_DELETE';

    const ROLE_API_COURSE_PREREQUISITE = 'ROLE_API_COURSE_PREREQUISITE';
    const ROLE_API_COURSE_PREREQUISITE_GET = 'ROLE_API_COURSE_PREREQUISITE_GET';
    const ROLE_API_COURSE_PREREQUISITE_POST = 'ROLE_API_COURSE_PREREQUISITE_POST';
    const ROLE_API_COURSE_PREREQUISITE_PUT = 'ROLE_API_COURSE_PREREQUISITE_PUT';
    const ROLE_API_COURSE_PREREQUISITE_DELETE = 'ROLE_API_COURSE_PREREQUISITE_DELETE';

    const ROLE_API_COURSE_RESOURCE_EQUIPMENT = 'ROLE_API_COURSE_RESOURCE_EQUIPMENT';
    const ROLE_API_COURSE_RESOURCE_EQUIPMENT_GET = 'ROLE_API_COURSE_RESOURCE_EQUIPMENT_GET';
    const ROLE_API_COURSE_RESOURCE_EQUIPMENT_POST = 'ROLE_API_COURSE_RESOURCE_EQUIPMENT_POST';
    const ROLE_API_COURSE_RESOURCE_EQUIPMENT_PUT = 'ROLE_API_COURSE_RESOURCE_EQUIPMENT_PUT';
    const ROLE_API_COURSE_RESOURCE_EQUIPMENT_DELETE = 'ROLE_API_COURSE_RESOURCE_EQUIPMENT_DELETE';

    const ROLE_API_COURSE_SECTION = 'ROLE_API_COURSE_SECTION';
    const ROLE_API_COURSE_SECTION_GET = 'ROLE_API_COURSE_SECTION_GET';
    const ROLE_API_COURSE_SECTION_POST = 'ROLE_API_COURSE_SECTION_POST';
    const ROLE_API_COURSE_SECTION_PUT = 'ROLE_API_COURSE_SECTION_PUT';
    const ROLE_API_COURSE_SECTION_DELETE = 'ROLE_API_COURSE_SECTION_DELETE';

    const ROLE_API_COURSE_SECTION_ACTIVITY = 'ROLE_API_COURSE_SECTION_ACTIVITY';
    const ROLE_API_COURSE_SECTION_ACTIVITY_GET = 'ROLE_API_COURSE_SECTION_ACTIVITY_GET';
    const ROLE_API_COURSE_SECTION_ACTIVITY_POST = 'ROLE_API_COURSE_SECTION_ACTIVITY_POST';
    const ROLE_API_COURSE_SECTION_ACTIVITY_PUT = 'ROLE_API_COURSE_SECTION_ACTIVITY_PUT';
    const ROLE_API_COURSE_SECTION_ACTIVITY_DELETE = 'ROLE_API_COURSE_SECTION_ACTIVITY_DELETE';

    const ROLE_API_COURSE_TEACHER = 'ROLE_API_COURSE_TEACHER';
    const ROLE_API_COURSE_TEACHER_GET = 'ROLE_API_COURSE_TEACHER_GET';
    const ROLE_API_COURSE_TEACHER_POST = 'ROLE_API_COURSE_TEACHER_POST';
    const ROLE_API_COURSE_TEACHER_PUT = 'ROLE_API_COURSE_TEACHER_PUT';
    const ROLE_API_COURSE_TEACHER_DELETE = 'ROLE_API_COURSE_TEACHER_DELETE';

    const ROLE_API_COURSE_TUTORING_RESOURCE = 'ROLE_API_COURSE_TUTORING_RESOURCE';
    const ROLE_API_COURSE_TUTORING_RESOURCE_GET = 'ROLE_API_COURSE_TUTORING_RESOURCE_GET';
    const ROLE_API_COURSE_TUTORING_RESOURCE_POST = 'ROLE_API_COURSE_TUTORING_RESOURCE_POST';
    const ROLE_API_COURSE_TUTORING_RESOURCE_PUT = 'ROLE_API_COURSE_TUTORING_RESOURCE_PUT';
    const ROLE_API_COURSE_TUTORING_RESOURCE_DELETE = 'ROLE_API_COURSE_TUTORING_RESOURCE_DELETE';

    const ROLE_API_CRITICAL_ACHIEVEMENT = 'ROLE_API_CRITICAL_ACHIEVEMENT';
    const ROLE_API_CRITICAL_ACHIEVEMENT_GET = 'ROLE_API_CRITICAL_ACHIEVEMENT_GET';
    const ROLE_API_CRITICAL_ACHIEVEMENT_POST = 'ROLE_API_CRITICAL_ACHIEVEMENT_POST';
    const ROLE_API_CRITICAL_ACHIEVEMENT_PUT = 'ROLE_API_CRITICAL_ACHIEVEMENT_PUT';
    const ROLE_API_CRITICAL_ACHIEVEMENT_DELETE = 'ROLE_API_CRITICAL_ACHIEVEMENT_DELETE';

    const ROLE_API_DOMAIN = 'ROLE_API_DOMAIN';
    const ROLE_API_DOMAIN_GET = 'ROLE_API_DOMAIN_GET';
    const ROLE_API_DOMAIN_POST = 'ROLE_API_DOMAIN_POST';
    const ROLE_API_DOMAIN_PUT = 'ROLE_API_DOMAIN_PUT';
    const ROLE_API_DOMAIN_DELETE = 'ROLE_API_DOMAIN_DELETE';

    const ROLE_API_EQUIPMENT = 'ROLE_API_EQUIPMENT';
    const ROLE_API_EQUIPMENT_GET = 'ROLE_API_EQUIPMENT_GET';
    const ROLE_API_EQUIPMENT_POST = 'ROLE_API_EQUIPMENT_POST';
    const ROLE_API_EQUIPMENT_PUT = 'ROLE_API_EQUIPMENT_PUT';
    const ROLE_API_EQUIPMENT_DELETE = 'ROLE_API_EQUIPMENT_DELETE';

    const ROLE_API_GROUPS = 'ROLE_API_GROUPS';
    const ROLE_API_GROUPS_GET = 'ROLE_API_GROUPS_GET';
    const ROLE_API_GROUPS_POST = 'ROLE_API_GROUPS_POST';
    const ROLE_API_GROUPS_PUT = 'ROLE_API_GROUPS_PUT';
    const ROLE_API_GROUPS_DELETE = 'ROLE_API_GROUPS_DELETE';

    const ROLE_API_JOB = 'ROLE_API_JOB';
    const ROLE_API_JOB_GET = 'ROLE_API_JOB_GET';
    const ROLE_API_JOB_POST = 'ROLE_API_JOB_POST';
    const ROLE_API_JOB_PUT = 'ROLE_API_JOB_PUT';
    const ROLE_API_JOB_DELETE = 'ROLE_API_JOB_DELETE';

    const ROLE_API_LANGUAGE = 'ROLE_API_LANGUAGE';
    const ROLE_API_LANGUAGE_GET = 'ROLE_API_LANGUAGE_GET';
    const ROLE_API_LANGUAGE_POST = 'ROLE_API_LANGUAGE_POST';
    const ROLE_API_LANGUAGE_PUT = 'ROLE_API_LANGUAGE_PUT';
    const ROLE_API_LANGUAGE_DELETE = 'ROLE_API_LANGUAGE_DELETE';

    const ROLE_API_LEARNING_ACHIEVEMENT = 'ROLE_API_LEARNING_ACHIEVEMENT';
    const ROLE_API_LEARNING_ACHIEVEMENT_GET = 'ROLE_API_LEARNING_ACHIEVEMENT_GET';
    const ROLE_API_LEARNING_ACHIEVEMENT_POST = 'ROLE_API_LEARNING_ACHIEVEMENT_POST';
    const ROLE_API_LEARNING_ACHIEVEMENT_PUT = 'ROLE_API_LEARNING_ACHIEVEMENT_PUT';
    const ROLE_API_LEARNING_ACHIEVEMENT_DELETE = 'ROLE_API_LEARNING_ACHIEVEMENT_DELETE';

    const ROLE_API_LEVEL = 'ROLE_API_LEVEL';
    const ROLE_API_LEVEL_GET = 'ROLE_API_LEVEL_GET';
    const ROLE_API_LEVEL_POST = 'ROLE_API_LEVEL_POST';
    const ROLE_API_LEVEL_PUT = 'ROLE_API_LEVEL_PUT';
    const ROLE_API_LEVEL_DELETE = 'ROLE_API_LEVEL_DELETE';

    const ROLE_API_NOTIFICATION = 'ROLE_API_NOTIFICATION';
    const ROLE_API_NOTIFICATION_GET = 'ROLE_API_NOTIFICATION_GET';
    const ROLE_API_NOTIFICATION_POST = 'ROLE_API_NOTIFICATION_POST';
    const ROLE_API_NOTIFICATION_PUT = 'ROLE_API_NOTIFICATION_PUT';
    const ROLE_API_NOTIFICATION_DELETE = 'ROLE_API_NOTIFICATION_DELETE';

    const ROLE_API_PERIOD = 'ROLE_API_PERIOD';
    const ROLE_API_PERIOD_GET = 'ROLE_API_PERIOD_GET';
    const ROLE_API_PERIOD_POST = 'ROLE_API_PERIOD_POST';
    const ROLE_API_PERIOD_PUT = 'ROLE_API_PERIOD_PUT';
    const ROLE_API_PERIOD_DELETE = 'ROLE_API_PERIOD_DELETE';

    const ROLE_API_STRUCTURE = 'ROLE_API_STRUCTURE';
    const ROLE_API_STRUCTURE_GET = 'ROLE_API_STRUCTURE_GET';
    const ROLE_API_STRUCTURE_POST = 'ROLE_API_STRUCTURE_POST';
    const ROLE_API_STRUCTURE_PUT = 'ROLE_API_STRUCTURE_PUT';
    const ROLE_API_STRUCTURE_DELETE = 'ROLE_API_STRUCTURE_DELETE';

    const ROLE_API_TEACHING = 'ROLE_API_TEACHING';
    const ROLE_API_TEACHING_GET = 'ROLE_API_TEACHING_GET';
    const ROLE_API_TEACHING_POST = 'ROLE_API_TEACHING_POST';
    const ROLE_API_TEACHING_PUT = 'ROLE_API_TEACHING_PUT';
    const ROLE_API_TEACHING_DELETE = 'ROLE_API_TEACHING_DELETE';

    const ROLE_API_USER = 'ROLE_API_USER';
    const ROLE_API_USER_GET = 'ROLE_API_USER_GET';
    const ROLE_API_USER_POST = 'ROLE_API_USER_POST';
    const ROLE_API_USER_PUT = 'ROLE_API_USER_PUT';
    const ROLE_API_USER_DELETE = 'ROLE_API_USER_DELETE';

    const ROLE_API_YEAR = 'ROLE_API_YEAR';
    const ROLE_API_YEAR_GET = 'ROLE_API_YEAR_GET';
    const ROLE_API_YEAR_POST = 'ROLE_API_YEAR_POST';
    const ROLE_API_YEAR_PUT = 'ROLE_API_YEAR_PUT';
    const ROLE_API_YEAR_DELETE = 'ROLE_API_YEAR_DELETE';

    /*====================== End ROLE API ==================*/

    const ROLES = [
        self::ROLE_USER,
        self::ROLE_SUPER_ADMIN,
        self::ROLE_ADMIN,
        self::ROLE_ADMIN_YEAR,
        self::ROLE_ADMIN_YEAR_LIST,
        self::ROLE_ADMIN_YEAR_CREATE,
        self::ROLE_ADMIN_YEAR_UPDATE,
        self::ROLE_ADMIN_COURSE,
        self::ROLE_ADMIN_COURSE_VIEW,
        self::ROLE_ADMIN_COURSE_LIST,
        self::ROLE_ADMIN_COURSE_CREATE,
        self::ROLE_ADMIN_COURSE_UPDATE,
        self::ROLE_ADMIN_COURSE_INFO,
        self::ROLE_ADMIN_COURSE_INFO_LIST,
        self::ROLE_ADMIN_COURSE_INFO_CREATE,
        self::ROLE_ADMIN_COURSE_INFO_UPDATE,
        self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT,
        self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_LIST,
        self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_CREATE,
        self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_UPDATE,
        self::ROLE_ADMIN_ACTIVITY,
        self::ROLE_ADMIN_ACTIVITY_LIST,
        self::ROLE_ADMIN_ACTIVITY_CREATE,
        self::ROLE_ADMIN_ACTIVITY_UPDATE,
        self::ROLE_ADMIN_ACTIVITYMODE,
        self::ROLE_ADMIN_ACTIVITYMODE_LIST,
        self::ROLE_ADMIN_ACTIVITYMODE_CREATE,
        self::ROLE_ADMIN_ACTIVITYMODE_UPDATE,
        self::ROLE_ADMIN_ACTIVITYTYPE,
        self::ROLE_ADMIN_ACTIVITYTYPE_LIST,
        self::ROLE_ADMIN_ACTIVITYTYPE_CREATE,
        self::ROLE_ADMIN_ACTIVITYTYPE_UPDATE,
        self::ROLE_ADMIN_CAMPUS,
        self::ROLE_ADMIN_CAMPUS_LIST,
        self::ROLE_ADMIN_CAMPUS_CREATE,
        self::ROLE_ADMIN_CAMPUS_UPDATE,
        self::ROLE_ADMIN_DOMAIN,
        self::ROLE_ADMIN_DOMAIN_LIST,
        self::ROLE_ADMIN_DOMAIN_CREATE,
        self::ROLE_ADMIN_DOMAIN_UPDATE,
        self::ROLE_ADMIN_EQUIPMENT,
        self::ROLE_ADMIN_EQUIPMENT_LIST,
        self::ROLE_ADMIN_EQUIPMENT_CREATE,
        self::ROLE_ADMIN_EQUIPMENT_UPDATE,
        self::ROLE_ADMIN_JOB,
        self::ROLE_ADMIN_JOB_LIST,
        self::ROLE_ADMIN_JOB_CREATE,
        self::ROLE_ADMIN_JOB_UPDATE,
        self::ROLE_ADMIN_JOB_DELETE,
        self::ROLE_ADMIN_JOB_EXECUTE,
        self::ROLE_ADMIN_JOB_REPORT,
        self::ROLE_ADMIN_LANGUAGE,
        self::ROLE_ADMIN_LANGUAGE_LIST,
        self::ROLE_ADMIN_LANGUAGE_CREATE,
        self::ROLE_ADMIN_LANGUAGE_UPDATE,
        self::ROLE_ADMIN_NOTIFICATION,
        self::ROLE_ADMIN_NOTIFICATION_LIST,
        self::ROLE_ADMIN_NOTIFICATION_CREATE,
        self::ROLE_ADMIN_NOTIFICATION_UPDATE,
        self::ROLE_ADMIN_NOTIFICATION_DELETE,
        self::ROLE_ADMIN_PERIOD,
        self::ROLE_ADMIN_PERIOD_LIST,
        self::ROLE_ADMIN_PERIOD_CREATE,
        self::ROLE_ADMIN_PERIOD_UPDATE,
        self::ROLE_ADMIN_STRUCTURE,
        self::ROLE_ADMIN_STRUCTURE_LIST,
        self::ROLE_ADMIN_STRUCTURE_CREATE,
        self::ROLE_ADMIN_STRUCTURE_UPDATE,
        self::ROLE_ADMIN_USER,
        self::ROLE_ADMIN_USER_LIST,
        self::ROLE_ADMIN_USER_CREATE,
        self::ROLE_ADMIN_USER_UPDATE,
        self::ROLE_ADMIN_LEVEL,
        self::ROLE_ADMIN_LEVEL_LIST,
        self::ROLE_ADMIN_LEVEL_CREATE,
        self::ROLE_ADMIN_LEVEL_UPDATE,
        self::ROLE_API,
        self::ROLE_API_ACTIVITY,
        self::ROLE_API_ACTIVITY_GET,
        self::ROLE_API_ACTIVITY_POST,
        self::ROLE_API_ACTIVITY_PUT,
        self::ROLE_API_ACTIVITY_DELETE,
        self::ROLE_API_ACTIVITY_MODE,
        self::ROLE_API_ACTIVITY_MODE_GET,
        self::ROLE_API_ACTIVITY_MODE_POST,
        self::ROLE_API_ACTIVITY_MODE_PUT,
        self::ROLE_API_ACTIVITY_MODE_DELETE,
        self::ROLE_API_ACTIVITY_TYPE,
        self::ROLE_API_ACTIVITY_TYPE_GET,
        self::ROLE_API_ACTIVITY_TYPE_POST,
        self::ROLE_API_ACTIVITY_TYPE_PUT,
        self::ROLE_API_ACTIVITY_TYPE_DELETE,
        self::ROLE_API_ASK_ADVICE,
        self::ROLE_API_ASK_ADVICE_GET,
        self::ROLE_API_ASK_ADVICE_POST,
        self::ROLE_API_ASK_ADVICE_PUT,
        self::ROLE_API_ASK_ADVICE_DELETE,
        self::ROLE_API_CAMPUS,
        self::ROLE_API_CAMPUS_GET,
        self::ROLE_API_CAMPUS_POST,
        self::ROLE_API_CAMPUS_PUT,
        self::ROLE_API_CAMPUS_DELETE,
        self::ROLE_API_COURSE,
        self::ROLE_API_COURSE_GET,
        self::ROLE_API_COURSE_POST,
        self::ROLE_API_COURSE_PUT,
        self::ROLE_API_COURSE_DELETE,
        self::ROLE_API_COURSE_ACHIEVEMENT,
        self::ROLE_API_COURSE_ACHIEVEMENT_GET,
        self::ROLE_API_COURSE_ACHIEVEMENT_POST,
        self::ROLE_API_COURSE_ACHIEVEMENT_PUT,
        self::ROLE_API_COURSE_ACHIEVEMENT_DELETE,
        self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT,
        self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_GET,
        self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_POST,
        self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_PUT,
        self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_DELETE,
        self::ROLE_API_COURSE_INFO,
        self::ROLE_API_COURSE_INFO_GET,
        self::ROLE_API_COURSE_INFO_POST,
        self::ROLE_API_COURSE_INFO_PUT,
        self::ROLE_API_COURSE_INFO_DELETE,
        self::ROLE_API_COURSE_INFO_FIELD,
        self::ROLE_API_COURSE_INFO_FIELD_GET,
        self::ROLE_API_COURSE_INFO_FIELD_POST,
        self::ROLE_API_COURSE_INFO_FIELD_PUT,
        self::ROLE_API_COURSE_INFO_FIELD_DELETE,
        self::ROLE_API_COURSE_PERMISSION,
        self::ROLE_API_COURSE_PERMISSION_GET,
        self::ROLE_API_COURSE_PERMISSION_POST,
        self::ROLE_API_COURSE_PERMISSION_PUT,
        self::ROLE_API_COURSE_PERMISSION_DELETE,
        self::ROLE_API_COURSE_PREREQUISITE,
        self::ROLE_API_COURSE_PREREQUISITE_GET,
        self::ROLE_API_COURSE_PREREQUISITE_POST,
        self::ROLE_API_COURSE_PREREQUISITE_PUT,
        self::ROLE_API_COURSE_PREREQUISITE_DELETE,
        self::ROLE_API_COURSE_RESOURCE_EQUIPMENT,
        self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_GET,
        self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_POST,
        self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_PUT,
        self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_DELETE,
        self::ROLE_API_COURSE_SECTION,
        self::ROLE_API_COURSE_SECTION_GET,
        self::ROLE_API_COURSE_SECTION_POST,
        self::ROLE_API_COURSE_SECTION_PUT,
        self::ROLE_API_COURSE_SECTION_DELETE,
        self::ROLE_API_COURSE_SECTION_ACTIVITY,
        self::ROLE_API_COURSE_SECTION_ACTIVITY_GET,
        self::ROLE_API_COURSE_SECTION_ACTIVITY_POST,
        self::ROLE_API_COURSE_SECTION_ACTIVITY_PUT,
        self::ROLE_API_COURSE_SECTION_ACTIVITY_DELETE,
        self::ROLE_API_COURSE_TEACHER,
        self::ROLE_API_COURSE_TEACHER_GET,
        self::ROLE_API_COURSE_TEACHER_POST,
        self::ROLE_API_COURSE_TEACHER_PUT,
        self::ROLE_API_COURSE_TEACHER_DELETE,
        self::ROLE_API_COURSE_TUTORING_RESOURCE,
        self::ROLE_API_COURSE_TUTORING_RESOURCE_GET,
        self::ROLE_API_COURSE_TUTORING_RESOURCE_POST,
        self::ROLE_API_COURSE_TUTORING_RESOURCE_PUT,
        self::ROLE_API_COURSE_TUTORING_RESOURCE_DELETE,
        self::ROLE_API_CRITICAL_ACHIEVEMENT,
        self::ROLE_API_CRITICAL_ACHIEVEMENT_GET,
        self::ROLE_API_CRITICAL_ACHIEVEMENT_POST,
        self::ROLE_API_CRITICAL_ACHIEVEMENT_PUT,
        self::ROLE_API_CRITICAL_ACHIEVEMENT_DELETE,
        self::ROLE_API_DOMAIN,
        self::ROLE_API_DOMAIN_GET,
        self::ROLE_API_DOMAIN_POST,
        self::ROLE_API_DOMAIN_PUT,
        self::ROLE_API_DOMAIN_DELETE,
        self::ROLE_API_EQUIPMENT,
        self::ROLE_API_EQUIPMENT_GET,
        self::ROLE_API_EQUIPMENT_POST,
        self::ROLE_API_EQUIPMENT_PUT,
        self::ROLE_API_EQUIPMENT_DELETE,
        self::ROLE_API_GROUPS,
        self::ROLE_API_GROUPS_GET,
        self::ROLE_API_GROUPS_POST,
        self::ROLE_API_GROUPS_PUT,
        self::ROLE_API_GROUPS_DELETE,
        self::ROLE_API_JOB,
        self::ROLE_API_JOB_GET,
        self::ROLE_API_JOB_POST,
        self::ROLE_API_JOB_PUT,
        self::ROLE_API_JOB_DELETE,
        self::ROLE_API_LANGUAGE,
        self::ROLE_API_LANGUAGE_GET,
        self::ROLE_API_LANGUAGE_POST,
        self::ROLE_API_LANGUAGE_PUT,
        self::ROLE_API_LANGUAGE_DELETE,
        self::ROLE_API_LEARNING_ACHIEVEMENT,
        self::ROLE_API_LEARNING_ACHIEVEMENT_GET,
        self::ROLE_API_LEARNING_ACHIEVEMENT_POST,
        self::ROLE_API_LEARNING_ACHIEVEMENT_PUT,
        self::ROLE_API_LEARNING_ACHIEVEMENT_DELETE,
        self::ROLE_API_LEVEL,
        self::ROLE_API_LEVEL_GET,
        self::ROLE_API_LEVEL_POST,
        self::ROLE_API_LEVEL_PUT,
        self::ROLE_API_LEVEL_DELETE,
        self::ROLE_API_NOTIFICATION,
        self::ROLE_API_NOTIFICATION_GET,
        self::ROLE_API_NOTIFICATION_POST,
        self::ROLE_API_NOTIFICATION_PUT,
        self::ROLE_API_NOTIFICATION_DELETE,
        self::ROLE_API_PERIOD,
        self::ROLE_API_PERIOD_GET,
        self::ROLE_API_PERIOD_POST,
        self::ROLE_API_PERIOD_PUT,
        self::ROLE_API_PERIOD_DELETE,
        self::ROLE_API_STRUCTURE,
        self::ROLE_API_STRUCTURE_GET,
        self::ROLE_API_STRUCTURE_POST,
        self::ROLE_API_STRUCTURE_PUT,
        self::ROLE_API_STRUCTURE_DELETE,
        self::ROLE_API_TEACHING,
        self::ROLE_API_TEACHING_GET,
        self::ROLE_API_TEACHING_POST,
        self::ROLE_API_TEACHING_PUT,
        self::ROLE_API_TEACHING_DELETE,
        self::ROLE_API_USER,
        self::ROLE_API_USER_GET,
        self::ROLE_API_USER_POST,
        self::ROLE_API_USER_PUT,
        self::ROLE_API_USER_DELETE,
        self::ROLE_API_YEAR,
        self::ROLE_API_YEAR_GET,
        self::ROLE_API_YEAR_POST,
        self::ROLE_API_YEAR_PUT,
        self::ROLE_API_YEAR_DELETE,
    ];

    const HIERARCHY = [
        self::ROLE_ADMIN => [
            self::ROLE_ADMIN_COURSE => [
                self::ROLE_ADMIN_COURSE_VIEW,
                self::ROLE_ADMIN_COURSE_LIST,
                self::ROLE_ADMIN_COURSE_CREATE,
                self::ROLE_ADMIN_COURSE_UPDATE
            ],
            self::ROLE_ADMIN_COURSE_INFO => [
                self::ROLE_ADMIN_COURSE_INFO_LIST,
                self::ROLE_ADMIN_COURSE_INFO_CREATE,
                self::ROLE_ADMIN_COURSE_INFO_UPDATE
            ],
            self::ROLE_ADMIN_YEAR => [
                self::ROLE_ADMIN_YEAR_LIST,
                self::ROLE_ADMIN_YEAR_CREATE,
                self::ROLE_ADMIN_YEAR_UPDATE
            ],
            self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT => [
                self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_LIST,
                self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_CREATE,
                self::ROLE_ADMIN_CRITICAL_ACHIEVEMENT_UPDATE
            ],
            self::ROLE_ADMIN_ACTIVITY => [
                self::ROLE_ADMIN_ACTIVITY_LIST,
                self::ROLE_ADMIN_ACTIVITY_CREATE,
                self::ROLE_ADMIN_ACTIVITY_UPDATE
            ],
            self::ROLE_ADMIN_ACTIVITYMODE => [
                self::ROLE_ADMIN_ACTIVITYMODE_LIST,
                self::ROLE_ADMIN_ACTIVITYMODE_CREATE,
                self::ROLE_ADMIN_ACTIVITYMODE_UPDATE
            ],
            self::ROLE_ADMIN_ACTIVITYTYPE => [
                self::ROLE_ADMIN_ACTIVITYTYPE_LIST,
                self::ROLE_ADMIN_ACTIVITYTYPE_CREATE,
                self::ROLE_ADMIN_ACTIVITYTYPE_UPDATE
            ],
            self::ROLE_ADMIN_CAMPUS => [
                self::ROLE_ADMIN_CAMPUS_LIST,
                self::ROLE_ADMIN_CAMPUS_CREATE,
                self::ROLE_ADMIN_CAMPUS_UPDATE
            ],
            self::ROLE_ADMIN_DOMAIN => [
                self::ROLE_ADMIN_DOMAIN_LIST,
                self::ROLE_ADMIN_DOMAIN_CREATE,
                self::ROLE_ADMIN_DOMAIN_UPDATE
            ],
            self::ROLE_ADMIN_EQUIPMENT => [
                self::ROLE_ADMIN_EQUIPMENT_LIST,
                self::ROLE_ADMIN_EQUIPMENT_CREATE,
                self::ROLE_ADMIN_EQUIPMENT_UPDATE
            ],
            self::ROLE_ADMIN_JOB => [
                self::ROLE_ADMIN_JOB_LIST,
                self::ROLE_ADMIN_JOB_CREATE,
                self::ROLE_ADMIN_JOB_UPDATE,
                self::ROLE_ADMIN_JOB_DELETE,
                self::ROLE_ADMIN_JOB_EXECUTE,
                self::ROLE_ADMIN_JOB_REPORT
            ],
            self::ROLE_ADMIN_LANGUAGE => [
                self::ROLE_ADMIN_LANGUAGE_LIST,
                self::ROLE_ADMIN_LANGUAGE_CREATE,
                self::ROLE_ADMIN_LANGUAGE_UPDATE
            ],
            self::ROLE_ADMIN_LEVEL => [
                self::ROLE_ADMIN_LEVEL_LIST,
                self::ROLE_ADMIN_LEVEL_CREATE,
                self::ROLE_ADMIN_LEVEL_UPDATE
            ],
            self::ROLE_ADMIN_NOTIFICATION => [
                self::ROLE_ADMIN_NOTIFICATION_LIST,
                self::ROLE_ADMIN_NOTIFICATION_CREATE,
                self::ROLE_ADMIN_NOTIFICATION_UPDATE,
                self::ROLE_ADMIN_NOTIFICATION_DELETE
            ],
            self::ROLE_ADMIN_PERIOD => [
                self::ROLE_ADMIN_PERIOD_LIST,
                self::ROLE_ADMIN_PERIOD_CREATE,
                self::ROLE_ADMIN_PERIOD_UPDATE
            ],
            self::ROLE_ADMIN_STRUCTURE => [
                self::ROLE_ADMIN_STRUCTURE_LIST,
                self::ROLE_ADMIN_STRUCTURE_CREATE,
                self::ROLE_ADMIN_STRUCTURE_UPDATE
            ],
            self::ROLE_ADMIN_USER => [
                self::ROLE_ADMIN_USER_LIST,
                self::ROLE_ADMIN_USER_CREATE,
                self::ROLE_ADMIN_USER_UPDATE
            ]
        ],
        self::ROLE_SUPER_ADMIN,
        self::ROLE_API => [
            self::ROLE_API_ACTIVITY => [
                self::ROLE_API_ACTIVITY_GET,
                self::ROLE_API_ACTIVITY_POST,
                self::ROLE_API_ACTIVITY_PUT,
                self::ROLE_API_ACTIVITY_DELETE,
            ],
            self::ROLE_API_ACTIVITY_MODE => [
                self::ROLE_API_ACTIVITY_MODE_GET,
                self::ROLE_API_ACTIVITY_MODE_POST,
                self::ROLE_API_ACTIVITY_MODE_PUT,
                self::ROLE_API_ACTIVITY_MODE_DELETE,
            ],
            self::ROLE_API_ACTIVITY_TYPE => [
                self::ROLE_API_ACTIVITY_TYPE_GET,
                self::ROLE_API_ACTIVITY_TYPE_POST,
                self::ROLE_API_ACTIVITY_TYPE_PUT,
                self::ROLE_API_ACTIVITY_TYPE_DELETE,
            ],
            self::ROLE_API_ASK_ADVICE => [
                self::ROLE_API_ASK_ADVICE_GET,
                self::ROLE_API_ASK_ADVICE_POST,
                self::ROLE_API_ASK_ADVICE_PUT,
                self::ROLE_API_ASK_ADVICE_DELETE,
            ],
            self::ROLE_API_CAMPUS => [
                self::ROLE_API_CAMPUS_GET,
                self::ROLE_API_CAMPUS_POST,
                self::ROLE_API_CAMPUS_PUT,
                self::ROLE_API_CAMPUS_DELETE,
            ],
            self::ROLE_API_COURSE => [
                self::ROLE_API_COURSE_GET,
                self::ROLE_API_COURSE_POST,
                self::ROLE_API_COURSE_PUT,
                self::ROLE_API_COURSE_DELETE,
            ],
            self::ROLE_API_COURSE_ACHIEVEMENT => [
                self::ROLE_API_COURSE_ACHIEVEMENT_GET,
                self::ROLE_API_COURSE_ACHIEVEMENT_POST,
                self::ROLE_API_COURSE_ACHIEVEMENT_PUT,
                self::ROLE_API_COURSE_ACHIEVEMENT_DELETE,
            ],
            self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT => [
                self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_GET,
                self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_POST,
                self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_PUT,
                self::ROLE_API_COURSE_CRITICAL_ACHIEVEMENT_DELETE,
            ],
            self::ROLE_API_COURSE_INFO => [
                self::ROLE_API_COURSE_INFO_GET,
                self::ROLE_API_COURSE_INFO_POST,
                self::ROLE_API_COURSE_INFO_PUT,
                self::ROLE_API_COURSE_INFO_DELETE,
            ],
            self::ROLE_API_COURSE_INFO_FIELD => [
                self::ROLE_API_COURSE_INFO_FIELD_GET,
                self::ROLE_API_COURSE_INFO_FIELD_POST,
                self::ROLE_API_COURSE_INFO_FIELD_PUT,
                self::ROLE_API_COURSE_INFO_FIELD_DELETE,
            ],
            self::ROLE_API_COURSE_PERMISSION => [
              self::ROLE_API_COURSE_PERMISSION_GET,
              self::ROLE_API_COURSE_PERMISSION_POST,
              self::ROLE_API_COURSE_PERMISSION_PUT,
              self::ROLE_API_COURSE_PERMISSION_DELETE,
            ],
            self::ROLE_API_COURSE_PREREQUISITE => [
                self::ROLE_API_COURSE_PREREQUISITE_GET,
                self::ROLE_API_COURSE_PREREQUISITE_POST,
                self::ROLE_API_COURSE_PREREQUISITE_PUT,
                self::ROLE_API_COURSE_PREREQUISITE_DELETE,
            ],
            self::ROLE_API_COURSE_RESOURCE_EQUIPMENT => [
                self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_GET,
                self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_POST,
                self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_PUT,
                self::ROLE_API_COURSE_RESOURCE_EQUIPMENT_DELETE,
            ],
            self::ROLE_API_COURSE_SECTION => [
                self::ROLE_API_COURSE_SECTION_GET,
                self::ROLE_API_COURSE_SECTION_POST,
                self::ROLE_API_COURSE_SECTION_PUT,
                self::ROLE_API_COURSE_SECTION_DELETE,
            ],
            self::ROLE_API_COURSE_SECTION_ACTIVITY => [
                self::ROLE_API_COURSE_SECTION_ACTIVITY_GET,
                self::ROLE_API_COURSE_SECTION_ACTIVITY_POST,
                self::ROLE_API_COURSE_SECTION_ACTIVITY_PUT,
                self::ROLE_API_COURSE_SECTION_ACTIVITY_DELETE,
            ],
            self::ROLE_API_COURSE_TEACHER => [
                self::ROLE_API_COURSE_TEACHER_GET,
                self::ROLE_API_COURSE_TEACHER_POST,
                self::ROLE_API_COURSE_TEACHER_PUT,
                self::ROLE_API_COURSE_TEACHER_DELETE,
            ],
            self::ROLE_API_COURSE_TUTORING_RESOURCE => [
                self::ROLE_API_COURSE_TUTORING_RESOURCE_GET,
                self::ROLE_API_COURSE_TUTORING_RESOURCE_POST,
                self::ROLE_API_COURSE_TUTORING_RESOURCE_PUT,
                self::ROLE_API_COURSE_TUTORING_RESOURCE_DELETE,
            ],
            self::ROLE_API_CRITICAL_ACHIEVEMENT => [
                self::ROLE_API_CRITICAL_ACHIEVEMENT_GET,
                self::ROLE_API_CRITICAL_ACHIEVEMENT_POST,
                self::ROLE_API_CRITICAL_ACHIEVEMENT_PUT,
                self::ROLE_API_CRITICAL_ACHIEVEMENT_DELETE,
            ],
            self::ROLE_API_DOMAIN => [
                self::ROLE_API_DOMAIN_GET,
                self::ROLE_API_DOMAIN_POST,
                self::ROLE_API_DOMAIN_PUT,
                self::ROLE_API_DOMAIN_DELETE,
            ],
            self::ROLE_API_EQUIPMENT => [
                self::ROLE_API_EQUIPMENT_GET,
                self::ROLE_API_EQUIPMENT_POST,
                self::ROLE_API_EQUIPMENT_PUT,
                self::ROLE_API_EQUIPMENT_DELETE,
            ],
            self::ROLE_API_GROUPS => [
                self::ROLE_API_GROUPS_GET,
                self::ROLE_API_GROUPS_POST,
                self::ROLE_API_GROUPS_PUT,
                self::ROLE_API_GROUPS_DELETE,
            ],
            self::ROLE_API_JOB => [
                self::ROLE_API_JOB_GET,
                self::ROLE_API_JOB_POST,
                self::ROLE_API_JOB_PUT,
                self::ROLE_API_JOB_DELETE,
            ],
            self::ROLE_API_LANGUAGE => [
                self::ROLE_API_LANGUAGE_GET,
                self::ROLE_API_LANGUAGE_POST,
                self::ROLE_API_LANGUAGE_PUT,
                self::ROLE_API_LANGUAGE_DELETE,
            ],
            self::ROLE_API_LEARNING_ACHIEVEMENT => [
                self::ROLE_API_LEARNING_ACHIEVEMENT_GET,
                self::ROLE_API_LEARNING_ACHIEVEMENT_POST,
                self::ROLE_API_LEARNING_ACHIEVEMENT_PUT,
                self::ROLE_API_LEARNING_ACHIEVEMENT_DELETE,
            ],
            self::ROLE_API_LEVEL => [
                self::ROLE_API_LEVEL_GET,
                self::ROLE_API_LEVEL_POST,
                self::ROLE_API_LEVEL_PUT,
                self::ROLE_API_LEVEL_DELETE,
            ],
            self::ROLE_API_NOTIFICATION => [
                self::ROLE_API_NOTIFICATION_GET,
                self::ROLE_API_NOTIFICATION_POST,
                self::ROLE_API_NOTIFICATION_PUT,
                self::ROLE_API_NOTIFICATION_DELETE,
            ],
            self::ROLE_API_PERIOD => [
                self::ROLE_API_PERIOD_GET,
                self::ROLE_API_PERIOD_POST,
                self::ROLE_API_PERIOD_PUT,
                self::ROLE_API_PERIOD_DELETE,
            ],
            self::ROLE_API_STRUCTURE => [
                self::ROLE_API_STRUCTURE_GET,
                self::ROLE_API_STRUCTURE_POST,
                self::ROLE_API_STRUCTURE_PUT,
                self::ROLE_API_STRUCTURE_DELETE,
            ],
            self::ROLE_API_TEACHING => [
                self::ROLE_API_TEACHING_GET,
                self::ROLE_API_TEACHING_POST,
                self::ROLE_API_TEACHING_PUT,
                self::ROLE_API_TEACHING_DELETE,
            ],
            self::ROLE_API_USER => [
                self::ROLE_API_USER_GET,
                self::ROLE_API_USER_POST,
                self::ROLE_API_USER_PUT,
                self::ROLE_API_USER_DELETE,
            ],
            self::ROLE_API_YEAR => [
                self::ROLE_API_YEAR_GET,
                self::ROLE_API_YEAR_POST,
                self::ROLE_API_YEAR_PUT,
                self::ROLE_API_YEAR_DELETE,
            ],
        ],
    ];
}