framework:
  cache:
    pools:
      app_cache_pool:
        default_lifetime: '%env(int:CACHE_LIFE_TIME)%'
        adapter: cache.adapter.filesystem
        tags: true
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system