doctrine:
  orm:
    auto_generate_proxy_classes: false
    default_entity_manager: syllabus
    entity_managers:
      app:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        connection: app
        metadata_cache_driver:
          type: pool
          pool: doctrine.system_cache_pool
        query_cache_driver:
          type: pool
          pool: doctrine.system_cache_pool
        result_cache_driver:
          type: pool
          pool: doctrine.result_cache_pool
        mappings:
          Syllabus:
            type: annotation
            is_bundle: false
            prefix: 'App\Syllabus\Entity'
            dir: "%kernel.project_dir%/src/Syllabus/Entity"
            alias: Syllabus
          translatable:
            type: annotation
            is_bundle: false
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
            alias: GedmoTranslatable
          DmishhSettingsBundle: ~