# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    locale: '%env(LOCALE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mailerSource: '%env(MAILER_SOURCE)%'
            $mailerTarget: '%env(MAILER_TARGET)%'
            $moodleApiUrl: '%env(MOODLE_API_URL)%'
            $moodleApiToken: '%env(MOODLE_API_TOKEN)%'
            $apogeeCourseNatureToImport: '%env(APOGEE_COURSE_NATURE_TO_IMPORT)%'

    App\Syllabus\:
        resource: '../src/Syllabus/*'
        exclude: '../src/Syllabus/{Entity,Tests, Client}'

    App\Syllabus\Controller\:
        resource: '../src/Syllabus/Controller'
        public: true
        tags: ['controller.service_arguments']

    # Twig Intl
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    # AUTHENTICATOR
    App\Syllabus\Security\Authenticator\TestAuthenticator:
        arguments: ['%test_authenticator%']

    # COMMAND
    #App\Syllabus\Importer\Course\CoursesDuplicateCommand:
    #    arguments: ['@syllabus_entity_manager']

    # ENTITY MANAGER
    syllabus_entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine', getManager]
        arguments: ['syllabus']

    # FACTORY
    App\Syllabus\Factory\ImportCourseTeacherFactory:
        arguments: [ '%course_teacher_factory%' ]

    # FORM
    App\Syllabus\Form\Course\EditPresentationCourseInfoType:
        arguments: [ '%course_teacher_factory%' ]

    App\Syllabus\Form\CourseInfo\Presentation\TeachersType:
        arguments: [ '%course_teacher_factory%' ]

    # FIXTURE
    App\Syllabus\Fixture\CourseFixture:
        tags: ['doctrine.fixture.orm']

    # HELPER
    App\Syllabus\Helper\FileUploaderHelper:
        arguments: [ '%data_directory%' ]
    App\Syllabus\Helper\FileRemoverHelper:
        arguments: ['@filesystem', '%data_directory%']

    # LISTENER
    App\Syllabus\Listener\CoursePresentationImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    App\Syllabus\Listener\NotificationListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    App\Syllabus\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # QUERY
    App\Syllabus\Query\CourseTeacher\Adapter\Ldap\SearchCourseTeacherLdapQuery:
        public: true
        autowire: true
    App\Syllabus\Query\CourseTeacher\Adapter\Ldap\FindCourseTeacherByIdLdapQuery:
        public: true
        autowire: true

    # PROVIDERS
    App\Syllabus\Security\Provider\TestUserProvider:
        arguments: ['%test_authenticator%']

    #JMS
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor

    Dmishh\SettingsBundle\Manager\SettingsManager:
        alias: settings_manager