services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mailerSource: '%mailer_source%'

    AppBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # GENERAL
    _instanceof:
        AppBundle\Action\ActionInterface:
            public: true
            autowire: true
            tags: ['controller.service_arguments']

    # ACTION
    AppBundle\Action\Ui\Course\AskForAdviceCourseInfoAction:
        arguments: ['%mailer_source%', '%mailer_target%']
    AppBundle\Action\Ui\Course\PublishCourseInfoAction:
        arguments: ['%mailer_source%', '%mailer_target%']

    # ALIAS
    AppBundle\Repository\UserRepositoryInterface: '@user_doctrine_repository'
    AppBundle\Repository\ActivityRepositoryInterface: '@activity_doctrine_repository'
    AppBundle\Repository\CourseRepositoryInterface: '@course_doctrine_repository'
    AppBundle\Repository\CourseAchievementRepositoryInterface: '@course_achievement_doctrine_repository'
    AppBundle\Repository\CourseInfoRepositoryInterface: '@course_info_doctrine_repository'
    AppBundle\Repository\CoursePrerequisiteRepositoryInterface: '@course_prerequisite_doctrine_repository'
    AppBundle\Repository\CourseResourceEquipmentRepositoryInterface: '@course_resource_equipment_doctrine_repository'
    AppBundle\Repository\CourseSectionRepositoryInterface: '@course_section_doctrine_repository'
    AppBundle\Repository\CourseSectionActivityRepositoryInterface: '@course_section_activity_doctrine_repository'
    AppBundle\Repository\CourseTeacherRepositoryInterface: '@course_teacher_doctrine_repository'
    AppBundle\Repository\CourseTutoringResourceRepositoryInterface: '@course_tutoring_resource_doctrine_repository'
    AppBundle\Repository\EquipmentRepositoryInterface: '@equipment_doctrine_repository'
    AppBundle\Repository\StructureRepositoryInterface: '@structure_doctrine_repository'
    AppBundle\Repository\YearRepositoryInterface: '@year_doctrine_repository'

    # AUTHENTICATOR
    AppBundle\Security\Authenticator\TestAuthenticator:
        arguments: ['%test_authenticator%']

    # COMMAND
    AppBundle\Importer\Course\CoursesDuplicateCommand:
        arguments: ['@syllabus_entity_manager']

    # ENTITY MANAGER
    syllabus_entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine', getManager]
        arguments: ['syllabus']

    # FACTORY
    AppBundle\Factory\ImportCourseTeacherFactory:
        arguments: [ '%course_teacher_factory%' ]

    # FORM
    AppBundle\Form\Course\EditPresentationCourseInfoType:
        arguments: [ '%course_teacher_factory%' ]

    AppBundle\Form\CourseInfo\Presentation\TeachersType:
        arguments: [ '%course_teacher_factory%' ]

    AppBundle\Form\CourseSectionActivity\CourseSectionActivityType:
        arguments: [ '@syllabus_entity_manager' ]

    AppBundle\Form\CourseResourceEquipment\CourseResourceEquipmentType:
        arguments: [ '@syllabus_entity_manager' ]

    # FIXTURE
    AppBundle\Fixture\CourseFixture:
        tags: ['doctrine.fixture.orm']

    # HELPER
    AppBundle\Helper\FileUploaderHelper:
        arguments: [ '%data_directory%' ]
    AppBundle\Helper\FileRemoverHelper:
        arguments: ['@filesystem', '%data_directory%']

    # LISTENER
    AppBundle\Listener\CoursePresentationImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    AppBundle\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # QUERY
    AppBundle\Query\CourseTeacher\Adapter\Ldap\SearchCourseTeacherLdapQuery:
        public: true
        autowire: true
    AppBundle\Query\CourseTeacher\Adapter\Ldap\FindCourseTeacherByIdLdapQuery:
        public: true
        autowire: true

    # REPOSITORY
    user_doctrine_repository:
        class: AppBundle\Repository\Doctrine\UserDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    activity_doctrine_repository:
        class: AppBundle\Repository\Doctrine\ActivityDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_achievement_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseAchievementDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_info_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseInfoDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_prerequisite_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CoursePrerequisiteDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_resource_equipment_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseResourceEquipmentDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_section_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseSectionDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_section_activity_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseSectionActivityDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_teacher_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseTeacherDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    course_tutoring_resource_doctrine_repository:
        class: AppBundle\Repository\Doctrine\CourseTutoringResourceDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    equipment_doctrine_repository:
        class: AppBundle\Repository\Doctrine\EquipmentDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    structure_doctrine_repository:
        class: AppBundle\Repository\Doctrine\StructureDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    year_doctrine_repository:
        class: AppBundle\Repository\Doctrine\YearDoctrineRepository
        arguments: ['@syllabus_entity_manager']

    # PROVIDERS
    AppBundle\Security\Provider\TestUserProvider:
        arguments: ['%test_authenticator%']

    #JMS
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor