AppBundle\Entity\Course:
    type: entity
    table: course
    uniqueConstraints:
        etb_id_UNIQUE:
            columns:
                - etb_id
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        type:
            type: string
            nullable: false
            length: 5
            options:
                fixed: true
        etbId:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            column: etb_id
    manyToMany:
        courseParent:
            targetEntity: Course
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: courseChild
            joinTable:
                name: course_hierarchy
                joinColumns:
                    -
                        name: course_child_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: course_parent_id
                        referencedColumnName: id
            orderBy: null
        courseChild:
            targetEntity: Course
            mappedBy: courseParent
    lifecycleCallbacks: {  }
