AppBundle\Entity\CourseSection:
    type: entity
    table: course_section
    indexes:
        fk_course_section_course_info1_idx:
            columns:
                - course_info_id
        fk_course_section_section_type1_idx:
            columns:
                - section_type_id
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        courseInfo:
            targetEntity: CourseInfo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_info_id:
                    referencedColumnName: id
            orphanRemoval: false
        sectionType:
            targetEntity: SectionType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                section_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
