AppBundle\Entity\CourseInfo:
    type: entity
    table: course_info
    indexes:
        fk_course_info_user2_idx:
            columns:
                - publisher
        fk_course_info_course1_idx:
            columns:
                - course_id
        fk_course_info_structure1_idx:
            columns:
                - structure_id
        fk_course_info_user1_idx:
            columns:
                - last_updater
        fk_course_info_year1_idx:
            columns:
                - year_id
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        ects:
            type: integer
            nullable: true
            options:
                unsigned: false
        level:
            type: string
            nullable: true
            length: 4
            options:
                fixed: true
        semester:
            type: integer
            nullable: true
            options:
                unsigned: false
        summary:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        period:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        image:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        video:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        teachingMode:
            type: string
            nullable: true
            length: 15
            options:
                fixed: true
            column: teaching_mode
        teachingCmClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_cm_class
        teachingTdClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_td_class
        teachingTpClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_tp_class
        teachingOtherClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_other_class
        teachingCmHybridClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_cm_hybrid_class
        teachingTdHybridClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_td_hybrid_class
        teachingTpHybridClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_tp_hybrid_class
        teachingOtherHybridClass:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_other_hybrid_class
        teachingCmHybridDist:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_cm_hybrid_dist
        teachingTdHybridDist:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_td_hybrid_dist
        teachingOtherHybridDist:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: teaching_other_hybrid_dist
        mccWeight:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: mcc_weight
        mccCapitalizable:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: mcc_capitalizable
        mccCcCoeffSession1:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: mcc_cc_coeff_session_1
        mccCcNbEvalSession1:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: mcc_cc_nb_eval_session_1
        mccCtCoeffSession1:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: mcc_ct_coeff_session_1
        mccCtNatSession1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: mcc_ct_nat_session_1
        mccCtDurationSession1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: mcc_ct_duration_session_1
        mccCtCoeffSession2:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: mcc_ct_coeff_session_2
        mccCtNatSession2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: mcc_ct_nat_session_2
        mccCtDurationSession2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: mcc_ct_duration_session_2
        mccAdvice:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: mcc_advice
        tutoring:
            type: boolean
            nullable: false
            options:
                default: '0'
        tutoringTeacher:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tutoring_teacher
        tutoringStudent:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tutoring_student
        tutoringDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tutoring_description
        educationalResources:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: educational_resources
        bibliographicResources:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: bibliographic_resources
        agenda:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        organization:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        closingRemarks:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: closing_remarks
        modificationDate:
            type: datetime
            nullable: true
            column: modification_date
        publicationDate:
            type: datetime
            nullable: true
            column: publication_date
        mediaType:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: media_type
    manyToOne:
        course:
            targetEntity: Course
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
        structure:
            targetEntity: Structure
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                structure_id:
                    referencedColumnName: id
            orphanRemoval: false
        lastUpdater:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                last_updater:
                    referencedColumnName: id
            orphanRemoval: false
        publisher:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                publisher:
                    referencedColumnName: id
            orphanRemoval: false
        year:
            targetEntity: Year
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                year_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
