AppBundle\Entity\CourseTeacher:
    type: entity
    table: course_teacher
    indexes:
        fk_course_teacher_course_info1_idx:
            columns:
                - course_info_id
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        firstname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        lastname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        manager:
            type: boolean
            nullable: false
            options:
                default: false
    manyToOne:
        courseInfo:
            targetEntity: CourseInfo
            cascade: [ 'persist' ]
            fetch: LAZY
            mappedBy: null
            inversedBy: courseTeachers
            joinColumns:
                course_info_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
