AppBundle\Entity\CourseSectionActivity:
    type: entity
    table: course_section_activity
    indexes:
        fk_course_section_activity_course_section1_idx:
            columns:
                - course_section_id
        fk_course_section_activity_activity1_idx:
            columns:
                - activity_id
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        order:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    manyToOne:
        activity:
            targetEntity: Activity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                activity_id:
                    referencedColumnName: id
            orphanRemoval: false
        courseSection:
            targetEntity: CourseSection
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_section_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
