AppBundle\Entity\Equipment:
    type: entity
    table: equipment
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        label:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        labelVisibility:
            type: boolean
            nullable: false
            options:
                default: true
            column: label_visibility
        icon:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        obsolete:
            type: boolean
            nullable: false
            options:
                default: false
        ord:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: 0
    lifecycleCallbacks: {  }
