AppBundle\Entity\SectionType:
    type: entity
    table: section_type
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        obsolete:
            type: boolean
            nullable: false
            options:
                default: '0'
        order:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
