AppBundle\Entity\Structure:
    type: entity
    table: structure
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        etbCode:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: etb_code
        label:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        campus:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        obsolete:
            type: boolean
            nullable: false
            options:
                default: '0'
    lifecycleCallbacks: {  }
