AppBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        username_UNIQUE:
            columns:
                - username
    id:
        id:
            type: string
            nullable: false
            length: 36
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        username:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        firstname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: true
        lastname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: true
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        roles:
            type: array
            nullable: true
    lifecycleCallbacks: {  }
