AppBundle\Entity\Year:
    type: entity
    table: year
    id:
        id:
            type: string
            nullable: false
            length: 4
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        label:
            type: string
            nullable: true
            length: 45
            options:
                fixed: true
        import:
            type: boolean
            nullable: true
            options:
                default: '0'
        edit:
            type: boolean
            nullable: true
            options:
                default: '0'
        current:
            type: boolean
            nullable: true
            options:
                default: '0'
    lifecycleCallbacks: {  }
