<?php


namespace AppBundle\Constant;


class UserRole
{
    const ROLE_USER = 'ROLE_USER';
    const ROLE_ADMIN = 'ROLE_ADMIN';

    /*====================== ROLE API ==================*/
    const ROLE_API = 'ROLE_API';

    const ROLE_API_GET_COURSE = 'ROLE_API_GET_COURSE';
    const ROLE_API_GET_COURSES = 'ROLE_API_GET_COURSES';
    const ROLE_API_POST_COURSE = 'ROLE_API_POST_COURSE';
    const ROLE_API_PUT_COURSE = 'ROLE_API_PUT_COURSE';

    const ROLE_API_GET_COURSE_INFO = 'ROLE_API_GET_COURSE_INFO';
    const ROLE_API_GET_COURSES_INFO = 'ROLE_API_GET_COURSES_INFO';
    const ROLE_API_POST_COURSE_INFO = 'ROLE_API_POST_COURSE_INFO';
    const ROLE_API_PUT_COURSE_INFO = 'ROLE_API_PUT_COURSE_INFO';

    const ROLE_API_GET_COURSE_PERMISSION = 'ROLE_API_GET_COURSE_PERMISSION';
    const ROLE_API_GET_COURSE_PERMISSIONS = 'ROLE_API_GET_COURSE_PERMISSIONS';
    const ROLE_API_POST_COURSE_PERMISSION = 'ROLE_API_POST_COURSE_PERMISSION';
    const ROLE_API_PUT_COURSE_PERMISSION = 'ROLE_API_PUT_COURSE_PERMISSION';

    const ROLE_API_GET_YEAR = 'ROLE_API_GET_YEAR';
    const ROLE_API_GET_YEARS = 'ROLE_API_GET_YEARS';
    const ROLE_API_POST_YEAR = 'ROLE_API_POST_YEAR';
    const ROLE_API_PUT_YEAR = 'ROLE_API_PUT_YEAR';
    /*====================== End ROLE API ==================*/

    const ROLES = [
        self::ROLE_USER,
        self::ROLE_ADMIN,
        self::ROLE_API,
    ];
}