imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: api_filters.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@LdapBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    fos_ck_editor.base_path: 'build/ckeditor'
    fos_ck_editor.js_path: 'build/ckeditor/ckeditor.js'
